import { Translations } from './lib/interfaces';
import {
  generateReverseTranslations,
  generateEncoder,
  generateDecoder,
} from './lib/generators';

// Edit enum name and contents
export enum EmergencyContactRelationship {
  Self = 'Self',
  Father = 'Father',
  Mother = 'Mother',
  Grandfather = 'Grandfather',
  Grandmother = 'Grandmother',
  ElderBrother = 'ElderBrother',
  ElderSister = 'ElderSister',
  Uncle = 'Uncle',
  Aunt = 'Aunt',
  Cousin = 'Cousin',
  Child = 'Child',
  Grandchild = 'Grandchild',
  Husband = 'Husband',
  Wife = 'Wife',
  FatherInLaw = 'FatherInLaw',
  MotherInLaw = 'MotherInLaw',
  ElderBrotherInLaw = 'ElderBrotherInLaw',
  ElderSisterInLaw = 'ElderSisterInLaw',
  YoungerBrotherInLaw = 'YoungerBrotherInLaw',
  YoungerSisterInLaw = 'YoungerSisterInLaw',
  OtherRelative = 'OtherRelative',
  Fiance = 'Fiance',
  Acquaintance = 'Acquaintance',
  Boss = 'Boss',
  Employer = 'Employer',
  Colleague = 'Colleague',
  Subordinate = 'Subordinate',
  Staff = 'Staff',
  YoungerBrother = 'YoungerBrother',
  YoungerSister = 'YoungerSister',
  StaffRelative = 'StaffRelative',
  StaffAcquaintance = 'StaffAcquaintance',
  JointContractor = 'JointContractor',
  JointContact = 'JointContact',
  Nephew = 'Nephew',
  Niece = 'Niece',
  AdoptedChild = 'AdoptedChild',
  ChildInLaw = 'ChildInLaw',
  CompanyRepresentative = 'CompanyRepresentative',
  Other = 'Other',
}

// Edit contexts
const translations: Translations = {
  ja: {
    [EmergencyContactRelationship.Self]: '本人',
    [EmergencyContactRelationship.Father]: '父',
    [EmergencyContactRelationship.Mother]: '母',
    [EmergencyContactRelationship.Grandfather]: '祖父',
    [EmergencyContactRelationship.Grandmother]: '祖母',
    [EmergencyContactRelationship.ElderBrother]: '兄',
    [EmergencyContactRelationship.ElderSister]: '姉',
    [EmergencyContactRelationship.Uncle]: 'おじ',
    [EmergencyContactRelationship.Aunt]: 'おば',
    [EmergencyContactRelationship.Cousin]: 'いとこ',
    [EmergencyContactRelationship.Child]: '子',
    [EmergencyContactRelationship.Grandchild]: '孫',
    [EmergencyContactRelationship.Husband]: '夫',
    [EmergencyContactRelationship.Wife]: '妻',
    [EmergencyContactRelationship.FatherInLaw]: '義父',
    [EmergencyContactRelationship.MotherInLaw]: '義母',
    [EmergencyContactRelationship.ElderBrotherInLaw]: '義兄',
    [EmergencyContactRelationship.ElderSisterInLaw]: '義姉',
    [EmergencyContactRelationship.YoungerBrotherInLaw]: '義弟',
    [EmergencyContactRelationship.YoungerSisterInLaw]: '義妹',
    [EmergencyContactRelationship.OtherRelative]: 'その他親族',
    [EmergencyContactRelationship.Fiance]: '婚約者',
    [EmergencyContactRelationship.Acquaintance]: '友人・知人',
    [EmergencyContactRelationship.Boss]: '上司',
    [EmergencyContactRelationship.Employer]: '雇用主',
    [EmergencyContactRelationship.Colleague]: '同僚',
    [EmergencyContactRelationship.Subordinate]: '部下',
    [EmergencyContactRelationship.Staff]: '社員',
    [EmergencyContactRelationship.YoungerBrother]: '弟',
    [EmergencyContactRelationship.YoungerSister]: '妹',
    [EmergencyContactRelationship.StaffRelative]: '社員の親族',
    [EmergencyContactRelationship.StaffAcquaintance]: '社員の知人',
    [EmergencyContactRelationship.JointContractor]: '連名契約者',
    [EmergencyContactRelationship.JointContact]: '連名連絡先',
    [EmergencyContactRelationship.Nephew]: '甥',
    [EmergencyContactRelationship.Niece]: '姪',
    [EmergencyContactRelationship.AdoptedChild]: '養子',
    [EmergencyContactRelationship.ChildInLaw]: '義子',
    [EmergencyContactRelationship.CompanyRepresentative]: '会社代表者',
    [EmergencyContactRelationship.Other]: 'その他',
  },
  en: {
    [EmergencyContactRelationship.Self]: 'Self',
    [EmergencyContactRelationship.Father]: 'Father',
    [EmergencyContactRelationship.Mother]: 'Mother',
    [EmergencyContactRelationship.Grandfather]: 'Grandfather',
    [EmergencyContactRelationship.Grandmother]: 'Grandmother',
    [EmergencyContactRelationship.ElderBrother]: 'Elder-brother',
    [EmergencyContactRelationship.ElderSister]: 'Elder-sister',
    [EmergencyContactRelationship.Uncle]: 'Uncle',
    [EmergencyContactRelationship.Aunt]: 'Aunt',
    [EmergencyContactRelationship.Cousin]: 'Cousin',
    [EmergencyContactRelationship.Child]: 'Child',
    [EmergencyContactRelationship.Grandchild]: 'Grandchild',
    [EmergencyContactRelationship.Husband]: 'Husband',
    [EmergencyContactRelationship.Wife]: 'Wife',
    [EmergencyContactRelationship.FatherInLaw]: 'Father-in-law',
    [EmergencyContactRelationship.MotherInLaw]: 'Mother-in-law',
    [EmergencyContactRelationship.ElderBrotherInLaw]: 'Elder-brother-in-law',
    [EmergencyContactRelationship.ElderSisterInLaw]: 'Elder-sister-in-law',
    [EmergencyContactRelationship.YoungerBrotherInLaw]: 'Younger-brother-in-law',
    [EmergencyContactRelationship.YoungerSisterInLaw]: 'Younger-sister-in-law',
    [EmergencyContactRelationship.OtherRelative]: 'Other relative',
    [EmergencyContactRelationship.Fiance]: 'Fiance',
    [EmergencyContactRelationship.Acquaintance]: 'Acquaintance',
    [EmergencyContactRelationship.Boss]: 'Boss',
    [EmergencyContactRelationship.Employer]: 'Employer',
    [EmergencyContactRelationship.Colleague]: 'Colleague',
    [EmergencyContactRelationship.Subordinate]: 'Subordinate',
    [EmergencyContactRelationship.Staff]: 'Staff',
    [EmergencyContactRelationship.YoungerBrother]: 'Younger-brother',
    [EmergencyContactRelationship.YoungerSister]: 'Younger-sister',
    [EmergencyContactRelationship.StaffRelative]: 'Staff\'s relative',
    [EmergencyContactRelationship.StaffAcquaintance]: 'Staff acquaintance',
    [EmergencyContactRelationship.JointContractor]: 'Joint contractor',
    [EmergencyContactRelationship.JointContact]: 'Joint contact',
    [EmergencyContactRelationship.Nephew]: 'Nephew',
    [EmergencyContactRelationship.Niece]: 'Niece',
    [EmergencyContactRelationship.AdoptedChild]: 'Adopted child',
    [EmergencyContactRelationship.ChildInLaw]: 'Child-in-law',
    [EmergencyContactRelationship.CompanyRepresentative]: 'Company representative',
    [EmergencyContactRelationship.Other]: 'Other',
  },
};

// DO NOT EDIT
const reverseTranslations = generateReverseTranslations(translations);

// Edit constants name
export const emergencyContactRelationshipEncoder = generateEncoder<EmergencyContactRelationship>(translations);
export const emergencyContactRelationshipDecoder = generateDecoder<EmergencyContactRelationship>(reverseTranslations);
