import { Translations } from './lib/interfaces';
import {
  generateReverseTranslations,
  generateEncoder,
  generateDecoder,
} from './lib/generators';

// Edit enum name and contents
export enum EmergencyContactRelationship {
  Self = 0,
  Father = 1,
  Mother = 2,
  Grandfather = 3,
  Grandmother = 4,
  ElderBrother = 5,
  ElderSister = 6,
  Uncle = 7,
  Aunt = 8,
  Cousin = 9,
  Child = 10,
  Grandchild = 11,
  Husband = 12,
  Wife = 13,
  FatherInLaw = 14,
  MotherInLaw = 15,
  ElderBrotherInLaw = 16,
  ElderSisterInLaw = 17,
  YoungerBrotherInLaw = 18,
  YoungerSisterInLaw = 19,
  OtherRelative = 20,
  Fiance = 21,
  Acquaintance = 22,
  Boss = 23,
  Employer = 24,
  Colleague = 25,
  Subordinate = 26,
  Staff = 27,
  YoungerBrother = 28,
  YoungerSister = 29,
  StaffRelative = 30,
  StaffAcquaintance = 31,
  JointContractor = 32,
  JointContact = 33,
  Nephew = 34,
  Niece = 35,
  AdoptedChild = 36,
  ChildInLaw = 37,
  CompanyRepresentative = 39,
  Other = 999,
}

// Edit contexts
const translations: Translations = {
  ja: {
    [EmergencyContactRelationship.Self]: '本人',
    [EmergencyContactRelationship.Father]: '父',
    [EmergencyContactRelationship.Mother]: '母',
    [EmergencyContactRelationship.Grandfather]: '祖父',
    [EmergencyContactRelationship.Grandmother]: '祖母',
    [EmergencyContactRelationship.ElderBrother]: '兄',
    [EmergencyContactRelationship.ElderSister]: '姉',
    [EmergencyContactRelationship.Uncle]: 'おじ',
    [EmergencyContactRelationship.Aunt]: 'おば',
    [EmergencyContactRelationship.Cousin]: 'いとこ',
    [EmergencyContactRelationship.Child]: '子',
    [EmergencyContactRelationship.Grandchild]: '孫',
    [EmergencyContactRelationship.Husband]: '夫',
    [EmergencyContactRelationship.Wife]: '妻',
    [EmergencyContactRelationship.FatherInLaw]: '義父',
    [EmergencyContactRelationship.MotherInLaw]: '義母',
    [EmergencyContactRelationship.ElderBrotherInLaw]: '義兄',
    [EmergencyContactRelationship.ElderSisterInLaw]: '義姉',
    [EmergencyContactRelationship.YoungerBrotherInLaw]: '義弟',
    [EmergencyContactRelationship.YoungerSisterInLaw]: '義妹',
    [EmergencyContactRelationship.OtherRelative]: 'その他親族',
    [EmergencyContactRelationship.Fiance]: '婚約者',
    [EmergencyContactRelationship.Acquaintance]: '友人・知人',
    [EmergencyContactRelationship.Boss]: '上司',
    [EmergencyContactRelationship.Employer]: '雇用主',
    [EmergencyContactRelationship.Colleague]: '同僚',
    [EmergencyContactRelationship.Subordinate]: '部下',
    [EmergencyContactRelationship.Staff]: '社員',
    [EmergencyContactRelationship.YoungerBrother]: '弟',
    [EmergencyContactRelationship.YoungerSister]: '妹',
    [EmergencyContactRelationship.StaffRelative]: '社員の親族',
    [EmergencyContactRelationship.StaffAcquaintance]: '社員の知人',
    [EmergencyContactRelationship.JointContractor]: '連名契約者',
    [EmergencyContactRelationship.JointContact]: '連名連絡先',
    [EmergencyContactRelationship.Nephew]: '甥',
    [EmergencyContactRelationship.Niece]: '姪',
    [EmergencyContactRelationship.AdoptedChild]: '養子',
    [EmergencyContactRelationship.ChildInLaw]: '義子',
    [EmergencyContactRelationship.CompanyRepresentative]: '会社代表者',
    [EmergencyContactRelationship.Other]: 'その他',
  },
  en: {
    [EmergencyContactRelationship.Self]: 'Self',
    [EmergencyContactRelationship.Father]: 'Father',
    [EmergencyContactRelationship.Mother]: 'Mother',
    [EmergencyContactRelationship.Grandfather]: 'Grandfather',
    [EmergencyContactRelationship.Grandmother]: 'Grandmother',
    [EmergencyContactRelationship.ElderBrother]: 'Elder-brother',
    [EmergencyContactRelationship.ElderSister]: 'Elder-sister',
    [EmergencyContactRelationship.Uncle]: 'Uncle',
    [EmergencyContactRelationship.Aunt]: 'Aunt',
    [EmergencyContactRelationship.Cousin]: 'Cousin',
    [EmergencyContactRelationship.Child]: 'Child',
    [EmergencyContactRelationship.Grandchild]: 'Grandchild',
    [EmergencyContactRelationship.Husband]: 'Husband',
    [EmergencyContactRelationship.Wife]: 'Wife',
    [EmergencyContactRelationship.FatherInLaw]: 'Father-in-law',
    [EmergencyContactRelationship.MotherInLaw]: 'Mother-in-law',
    [EmergencyContactRelationship.ElderBrotherInLaw]: 'Elder-brother-in-law',
    [EmergencyContactRelationship.ElderSisterInLaw]: 'Elder-sister-in-law',
    [EmergencyContactRelationship.YoungerBrotherInLaw]: 'Younger-brother-in-law',
    [EmergencyContactRelationship.YoungerSisterInLaw]: 'Younger-sister-in-law',
    [EmergencyContactRelationship.OtherRelative]: 'Other relative',
    [EmergencyContactRelationship.Fiance]: 'Fiance',
    [EmergencyContactRelationship.Acquaintance]: 'Acquaintance',
    [EmergencyContactRelationship.Boss]: 'Boss',
    [EmergencyContactRelationship.Employer]: 'Employer',
    [EmergencyContactRelationship.Colleague]: 'Colleague',
    [EmergencyContactRelationship.Subordinate]: 'Subordinate',
    [EmergencyContactRelationship.Staff]: 'Staff',
    [EmergencyContactRelationship.YoungerBrother]: 'Younger-brother',
    [EmergencyContactRelationship.YoungerSister]: 'Younger-sister',
    [EmergencyContactRelationship.StaffRelative]: 'Staff\'s relative',
    [EmergencyContactRelationship.StaffAcquaintance]: 'Staff acquaintance',
    [EmergencyContactRelationship.JointContractor]: 'Joint contractor',
    [EmergencyContactRelationship.JointContact]: 'Joint contact',
    [EmergencyContactRelationship.Nephew]: 'Nephew',
    [EmergencyContactRelationship.Niece]: 'Niece',
    [EmergencyContactRelationship.AdoptedChild]: 'Adopted child',
    [EmergencyContactRelationship.ChildInLaw]: 'Child-in-law',
    [EmergencyContactRelationship.CompanyRepresentative]: 'Company representative',
    [EmergencyContactRelationship.Other]: 'Other',
  },
};

// DO NOT EDIT
const reverseTranslations = generateReverseTranslations(translations);

// Edit constants name
export const emergencyContactRelationshipEncoder = generateEncoder<EmergencyContactRelationship>(translations);
export const emergencyContactRelationshipDecoder = generateDecoder<EmergencyContactRelationship>(reverseTranslations);
