import { Translations } from './lib/interfaces';
import {
  generateReverseTranslations,
  generateEncoder,
  generateDecoder,
} from './lib/generators';

// Edit enum name and contents
export enum Prefecture {
  Hokkaido = 'Hokkaido',
  Aomori = 'Aomori',
  Iwate = 'Iwate',
  Miyagi = 'Miyagi',
  Akita = 'Akita',
  Yamagata = 'Yamagata',
  Fukushima = 'Fukushima',
  Ibaraki = 'Ibaraki',
  Tochigi = 'Tochigi',
  Gunma = 'Gunma',
  Saitama = 'Saitama',
  Chiba = 'Chiba',
  Tokyo = 'Tokyo',
  Kanagawa = 'Kanagawa',
  Niigata = 'Niigata',
  Toyama = 'Toyama',
  Ishikawa = 'Ishikawa',
  Fukui = 'Fukui',
  Yamanashi = 'Yamanashi',
  Nagano = 'Nagano',
  Gifu = 'Gifu',
  Shizuoka = 'Shizuoka',
  Aichi = 'Aichi',
  Mie = 'Mie',
  Shiga = 'Shiga',
  Kyoto = 'Kyoto',
  Osaka = 'Osaka',
  Hyogo = 'Hyogo',
  Nara = 'Nara',
  Wakayama = 'Wakayama',
  Tottori = 'Tottori',
  Shimane = 'Shimane',
  Okayama = 'Okayama',
  Hiroshima = 'Hiroshima',
  Yamaguchi = 'Yamaguchi',
  Tokushima = 'Tokushima',
  Kagawa = 'Kagawa',
  Ehime = 'Ehime',
  Kochi = 'Kochi',
  Fukuoka = 'Fukuoka',
  Saga = 'Saga',
  Nagasaki = 'Nagasaki',
  Kumamoto = 'Kumamoto',
  Oita = 'Oita',
  Miyazaki = 'Miyazaki',
  Kagoshima = 'Kagoshima',
  Okinawa = 'Okinawa',
}

// Edit contexts
const translations: Translations = {
  ja: {
    [Prefecture.Hokkaido]: '北海道',
    [Prefecture.Aomori]: '青森県',
    [Prefecture.Iwate]: '岩手県',
    [Prefecture.Miyagi]: '宮城県',
    [Prefecture.Akita]: '秋田県',
    [Prefecture.Yamagata]: '山形県',
    [Prefecture.Fukushima]: '福島県',
    [Prefecture.Ibaraki]: '茨城県',
    [Prefecture.Tochigi]: '栃木県',
    [Prefecture.Gunma]: '群馬県',
    [Prefecture.Saitama]: '埼玉県',
    [Prefecture.Chiba]: '千葉県',
    [Prefecture.Tokyo]: '東京都',
    [Prefecture.Kanagawa]: '神奈川県',
    [Prefecture.Niigata]: '新潟県',
    [Prefecture.Toyama]: '富山県',
    [Prefecture.Ishikawa]: '石川県',
    [Prefecture.Fukui]: '福井県',
    [Prefecture.Yamanashi]: '山梨県',
    [Prefecture.Nagano]: '長野県',
    [Prefecture.Gifu]: '岐阜県',
    [Prefecture.Shizuoka]: '静岡県',
    [Prefecture.Aichi]: '愛知県',
    [Prefecture.Mie]: '三重県',
    [Prefecture.Shiga]: '滋賀県',
    [Prefecture.Kyoto]: '京都府',
    [Prefecture.Osaka]: '大阪府',
    [Prefecture.Hyogo]: '兵庫県',
    [Prefecture.Nara]: '奈良県',
    [Prefecture.Wakayama]: '和歌山県',
    [Prefecture.Tottori]: '鳥取県',
    [Prefecture.Shimane]: '島根県',
    [Prefecture.Okayama]: '岡山県',
    [Prefecture.Hiroshima]: '広島県',
    [Prefecture.Yamaguchi]: '山口県',
    [Prefecture.Tokushima]: '徳島県',
    [Prefecture.Kagawa]: '香川県',
    [Prefecture.Ehime]: '愛媛県',
    [Prefecture.Kochi]: '高知県',
    [Prefecture.Fukuoka]: '福岡県',
    [Prefecture.Saga]: '佐賀県',
    [Prefecture.Nagasaki]: '長崎県',
    [Prefecture.Kumamoto]: '熊本県',
    [Prefecture.Oita]: '大分県',
    [Prefecture.Miyazaki]: '宮崎県',
    [Prefecture.Kagoshima]: '鹿児島県',
    [Prefecture.Okinawa]: '沖縄県',
  },
  en: {
    [Prefecture.Hokkaido]: 'Hokkaido',
    [Prefecture.Aomori]: 'Aomori',
    [Prefecture.Iwate]: 'Iwate',
    [Prefecture.Miyagi]: 'Miyagi',
    [Prefecture.Akita]: 'Akita',
    [Prefecture.Yamagata]: 'Yamagata',
    [Prefecture.Fukushima]: 'Fukushima',
    [Prefecture.Ibaraki]: 'Ibaraki',
    [Prefecture.Tochigi]: 'Tochigi',
    [Prefecture.Gunma]: 'Gunma',
    [Prefecture.Saitama]: 'Saitama',
    [Prefecture.Chiba]: 'Chiba',
    [Prefecture.Tokyo]: 'Tokyo',
    [Prefecture.Kanagawa]: 'Kanagawa',
    [Prefecture.Niigata]: 'Niigata',
    [Prefecture.Toyama]: 'Toyama',
    [Prefecture.Ishikawa]: 'Ishikawa',
    [Prefecture.Fukui]: 'Fukui',
    [Prefecture.Yamanashi]: 'Yamanashi',
    [Prefecture.Nagano]: 'Nagano',
    [Prefecture.Gifu]: 'Gifu',
    [Prefecture.Shizuoka]: 'Shizuoka',
    [Prefecture.Aichi]: 'Aichi',
    [Prefecture.Mie]: 'Mie',
    [Prefecture.Shiga]: 'Shiga',
    [Prefecture.Kyoto]: 'Kyoto',
    [Prefecture.Osaka]: 'Osaka',
    [Prefecture.Hyogo]: 'Hyogo',
    [Prefecture.Nara]: 'Nara',
    [Prefecture.Wakayama]: 'Wakayama',
    [Prefecture.Tottori]: 'Tottori',
    [Prefecture.Shimane]: 'Shimane',
    [Prefecture.Okayama]: 'Okayama',
    [Prefecture.Hiroshima]: 'Hiroshima',
    [Prefecture.Yamaguchi]: 'Yamaguchi',
    [Prefecture.Tokushima]: 'Tokushima',
    [Prefecture.Kagawa]: 'Kagawa',
    [Prefecture.Ehime]: 'Ehime',
    [Prefecture.Kochi]: 'Kochi',
    [Prefecture.Fukuoka]: 'Fukuoka',
    [Prefecture.Saga]: 'Saga',
    [Prefecture.Nagasaki]: 'Nagasaki',
    [Prefecture.Kumamoto]: 'Kumamoto',
    [Prefecture.Oita]: 'Oita',
    [Prefecture.Miyazaki]: 'Miyazaki',
    [Prefecture.Kagoshima]: 'Kagoshima',
    [Prefecture.Okinawa]: 'Okinawa',
  },
};

// DO NOT EDIT
const reverseTranslations = generateReverseTranslations(translations);

// Edit constants name
export const prefectureEncoder = generateEncoder<Prefecture>(translations);
export const prefectureDecoder = generateDecoder<Prefecture>(
  reverseTranslations,
);
